version: '3.1'


#CONFIG MONGODB MONGO-EXPRESS
services:
  mongo:
    image: mongo
    container_name: mongo
    #restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: adminmongo
    networks:
      - mongo-networks
    volumes:
      - dbmongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: adminmongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminmongo
      ME_CONFIG_MONGODB_URL: mongodb://root:adminmongo@mongo:27017/
    networks:
      - mongo-networks
   

networks:
  mongo-networks:
    driver: bridge

volumes:
  dbmongo:
 
