version: '3'
services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: vollmed_api

        ports:
            - "3306:3306"
        volumes:
            - dbMysql:/var/lib/mysql

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - dbPostgres:/var/lib/postgresql/data

volumes:
    portainer_data:
    dbMysql:
    dbPostgres:
