version: '3'
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: vollmed_api

        ports:
            - "3306:3306"
        volumes:
            - dbMysql:/var/lib/mysql

volumes:
    dbMysql:

